# Generated by `free-agents deploy --replit` / `agent-toolbox deploy --replit`.
{ pkgs }: {
  deps = [
    # Module ID pinned in .replit (python-3.10:v18-20230807-322e88b) must match a working Python stack.
    # If import / environment fails after a Replit update, find the current module id at:
    # https://replit.com/languages/python
    pkgs.python310
  ];
}
