# REPLIT_FRICTION_LOG
# -----------------------------------------------------------------------------
# 1) Import URL shape
#    Spec: open https://replit.new/{github-url}. Official docs only describe
#    https://replit.com/github.com/owner/repo for "rapid import". Tried curl -I on
#    https://replit.new/github.com/owner/repo — HTTP 302 via new-redirector-util.replit.app.
#    Embedding a full URL as one path segment (URL-encoded https://...) also 302'd but
#    produced an awkward //https://... location. Chose replit.new/github.com/owner/repo
#    parsed from the remote so the browser opens a single stable pattern; noted mismatch
#    with literal "{full github-url}" in the spec.
#
# 2) replit.toml vs .replit
#    User asked for "replit.nix or replit.toml". Replit's configuration doc names .replit
#    (TOML, often hidden) plus replit.nix; no first-party "replit.toml" file in that doc.
#    Did not create replit.toml to avoid an undocumented duplicate config surface; only
#    .replit + replit.nix are generated when missing.
#
# 3) Pinned python module id
#    Docs example uses modules = ["python-3.10:v18-20230807-322e88b"]. Replit may rotate
#    these strings; there is no CLI/API in-repo to resolve the latest id, so we copied the
#    documented example and accept that it may need manual refresh if imports fail.
#
# 4) Run command vs packaged install
#    Gateway entry in this repo is uvicorn app.main:app (see scripts/dev-restart.sh, README).
#    For GitHub import, dependencies come from pyproject.toml; used `pip install -e .` on
#    onBoot plus uvicorn on Run so the repl matches editable dev layout without publishing
#    to PyPI inside the repl.
#
# 5) Node / monorepo
#    package.json lives under frontend/ only; gateway is Python-only. Did not add Node to
#    replit.nix since the stated goal is the Free Agents API gateway, not the Next.js app.
#
# 6) Git on Replit: stale lock + blocked .git writes + broken .replit during rebase
#    After pull/rebase/merge, an empty or stale lock under .git (e.g. index.lock) can block
#    every git command until removed manually in Shell. Separately, the Repl environment
#    sometimes refuses writes to .git (IDE Git panel then can't fetch/commit); only Shell
#    may work, or a Repl restart may be needed. Merge conflict markers inside .replit break
#    TOML parsing → Nix environment fails to build; fix file then git rebase --abort or
#    reset --hard origin/main. Replit Git UI shows "Unsupported state: middle of a rebase"
#    until rebase is finished or aborted. No Replit API surfaced in-product to clear locks.
# -----------------------------------------------------------------------------
from __future__ import annotations

import re
import subprocess
import sys
import webbrowser
from pathlib import Path
from typing import Optional, Tuple
from urllib.parse import urlparse

REPLIT_NEW_BASE = "https://replit.new"

# From https://docs.replit.com/replit-app/configuration (example template).
DOT_REPLIT_TEMPLATE = '''# Generated by `free-agents deploy --replit` / `agent-toolbox deploy --replit`.
# Free Agents (agent-toolbox) gateway — see README and app/cli.py.

entrypoint = "app/main.py"

# Pin matches Replit docs example; update if Replit deprecates this module id.
modules = ["python-3.10:v18-20230807-322e88b"]

[nix]
channel = "stable-23_11"

[packager]
language = "python3"

[packager.features]
guessImports = true

# Editable install on boot: -q is fast on no-op; --disable-pip-version-check avoids slow checks.
# Skips heavy work when nothing changed; still reapplies if pyproject.toml / deps change.
onBoot = "python3 -m pip install -q --upgrade pip --disable-pip-version-check && python3 -m pip install -q -e . --disable-pip-version-check"

run = ["bash", "-c", "exec python3 -m uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-4280}"]

[[ports]]
localPort = 4280
externalPort = 80

[gitHubImport]
requiredFiles = [".replit", "replit.nix"]
'''

REPLIT_NIX_TEMPLATE = """# Generated by `free-agents deploy --replit` / `agent-toolbox deploy --replit`.
{ pkgs }: {
  deps = [
    # Module ID pinned in .replit (python-3.10:v18-20230807-322e88b) must match a working Python stack.
    # If import / environment fails after a Replit update, find the current module id at:
    # https://replit.com/languages/python
    pkgs.python310
  ];
}
"""


def _run_git(args: list[str], *, cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        check=False,
    )


def _ensure_git_repo(root: Path) -> None:
    git_dir = root / ".git"
    probe = _run_git(["rev-parse", "--git-dir"], cwd=root)
    if probe.returncode != 0 or not git_dir.exists():
        print("Error: not a git repository (no .git or git rev-parse failed).", file=sys.stderr)
        if probe.stderr.strip():
            print(probe.stderr.strip(), file=sys.stderr)
        sys.exit(2)


def _normalize_git_remote_to_https(url: str) -> Optional[str]:
    u = url.strip()
    if not u:
        return None
    # git@github.com:org/repo.git
    if u.startswith("git@github.com:"):
        path = u.split(":", 1)[1].removesuffix(".git")
        return f"https://github.com/{path}"
    if u.startswith("ssh://git@github.com/"):
        path = u.removeprefix("ssh://git@github.com/").removesuffix(".git").lstrip("/")
        return f"https://github.com/{path}"
    if "github.com" not in u.lower():
        return None
    if u.startswith("git://github.com/"):
        path = u.removeprefix("git://github.com/").removesuffix(".git")
        return f"https://github.com/{path}"
    if u.startswith("https://github.com/") or u.startswith("http://github.com/"):
        parsed = urlparse(u)
        if not parsed.path or parsed.path == "/":
            return None
        path = parsed.path.strip("/").removesuffix(".git")
        if not re.fullmatch(r"[^/]+/[^/]+", path):
            return None
        return f"https://github.com/{path}"
    return None


def _parse_git_remote_v_fetch(line: str) -> Optional[Tuple[str, str]]:
    """Return (remote_name, url) for lines like 'origin  https://github.com/a/b.git (fetch)'."""
    s = line.strip()
    if not s.endswith("(fetch)"):
        return None
    core = s[: s.rindex("(fetch)")].strip()
    bits = core.split(None, 1)
    if len(bits) != 2:
        return None
    return bits[0], bits[1]


def _discover_github_https_url(root: Path) -> str:
    proc = _run_git(["remote", "-v"], cwd=root)
    if proc.returncode != 0:
        print("Error: `git remote -v` failed.", file=sys.stderr)
        print(proc.stderr.strip(), file=sys.stderr)
        sys.exit(2)
    candidates: list[Tuple[int, str]] = []
    for line in proc.stdout.splitlines():
        parsed = _parse_git_remote_v_fetch(line)
        if not parsed:
            continue
        name, raw_url = parsed
        url = _normalize_git_remote_to_https(raw_url)
        if not url:
            continue
        priority = 0 if name == "origin" else 1
        candidates.append((priority, url))
    if not candidates:
        print(
            "Error: no GitHub remote found. Add one with: git remote add origin https://github.com/ORG/REPO.git",
            file=sys.stderr,
        )
        sys.exit(2)
    candidates.sort(key=lambda x: (x[0], x[1]))
    return candidates[0][1]


def _owner_repo(github_https: str) -> Tuple[str, str]:
    # https://github.com/o/r -> (o, r)
    path = urlparse(github_https).path.strip("/").removesuffix(".git")
    parts = path.split("/")
    if len(parts) != 2:
        print(f"Error: could not parse owner/repo from {github_https!r}", file=sys.stderr)
        sys.exit(2)
    return parts[0], parts[1]


def _replit_import_url(github_https: str) -> str:
    owner, repo = _owner_repo(github_https)
    return f"{REPLIT_NEW_BASE}/github.com/{owner}/{repo}"


def _write_if_absent(path: Path, content: str, label: str) -> None:
    if path.exists():
        print(f"Keep existing {label}: {path}")
        return
    path.write_text(content, encoding="utf-8")
    print(f"Wrote {label}: {path}")


def _maybe_write_replit_nix(root: Path) -> None:
    nix = root / "replit.nix"
    toml = root / "replit.toml"
    if nix.exists() or toml.exists():
        if nix.exists():
            print(f"Keep existing replit.nix: {nix}")
        if toml.exists():
            print(f"Keep existing replit.toml: {toml}")
        return
    nix.write_text(REPLIT_NIX_TEMPLATE, encoding="utf-8")
    print(f"Wrote replit.nix: {nix}")


def _print_replit_secrets() -> None:
    print()
    print("Add these in Replit (Tools → Secrets). Do not commit values to git.")
    print("Names and purpose only:")
    print()
    rows = [
        ("OPENROUTER_API_KEY", "OpenRouter API key when PROVIDER is openrouter (real LLM responses)."),
        ("OPENROUTER_MODEL", "Optional model id (e.g. openai/gpt-4o-mini); defaults if unset."),
        ("OPENAI_API_KEY", "OpenAI API key when PROVIDER is openai."),
        ("PROVIDER", "LLM backend: stub, openrouter, or openai."),
        ("AGENT_PRESET", "Which bundled preset the gateway runs (e.g. summarizer)."),
        ("AUTH_TOKEN", "Optional shared secret; clients send Authorization: Bearer … if set."),
        ("DATABASE_URL", "Postgres connection string; use for durable DB on Replit (optional)."),
        ("SUPABASE_DATABASE_URL", "Alternate env name for Postgres (either this or DATABASE_URL)."),
        ("GITHUB_CLIENT_ID", "GitHub OAuth app client id for /github/oauth flows."),
        ("GITHUB_CLIENT_SECRET", "GitHub OAuth app secret for token exchange."),
        (
            "GITHUB_OAUTH_REDIRECT_URI",
            "Must be https://<your-repl-host>/github/oauth/callback (exact match in GitHub app).",
        ),
        ("GITHUB_TOKEN", "Optional PAT for GitHub repository tools in agents."),
        ("CLERK_JWKS_URL", "Clerk JWKS URL for verifying browser JWTs (if using Clerk with the API)."),
        ("CLERK_JWT_KEY", "PEM alternative to JWKS when verifying Clerk session JWTs."),
        ("CLERK_ISSUER", "Clerk JWT iss claim (frontend and gateway must match)."),
        ("CLERK_AUDIENCE", "Optional JWT aud override when your tokens use a custom audience."),
        ("CLERK_AUTHORIZED_PARTIES", "Comma-separated allowed frontend origins for Clerk tokens."),
        ("CLERK_SECRET_KEY", "Clerk secret key on the server for Clerk-backed GitHub account access."),
        ("CORS_ORIGINS", "Comma-separated browser origins allowed to call the API (production frontends)."),
        ("PORT", "Replit usually sets this; gateway listens on this port (default 4280 if unset)."),
    ]
    for name, desc in rows:
        print(f"  • {name}: {desc}")
    print()


def run_deploy_replit(*, root: Optional[Path] = None) -> None:
    """Prepare Replit config files and open the import URL. Mutates cwd’s project root only."""
    root = (root or Path.cwd()).resolve()
    _ensure_git_repo(root)
    github_https = _discover_github_https_url(root)
    print(f"GitHub remote: {github_https}")

    _write_if_absent(root / ".replit", DOT_REPLIT_TEMPLATE, ".replit")
    _maybe_write_replit_nix(root)

    _print_replit_secrets()

    open_url = _replit_import_url(github_https)
    print(f"Opening browser: {open_url}")
    webbrowser.open(open_url)

    print()
    print("After Replit opens:")
    print("Step 1: Add your secrets in Replit (Tools → Secrets)")
    print("Step 2: Click Run")
    print("Step 3: Your Free Agents gateway is live")
    print()
