# Replit deployment friction notes: docs/replit-friction-log.md (REPLIT_FRICTION_LOG).
from __future__ import annotations

import json
import re
import sys
import webbrowser
from pathlib import Path
from typing import Any, Optional, Tuple
from urllib.parse import urlparse

from app.storage import registry_store

REPLIT_NEW_BASE = "https://replit.new"
DEFAULT_GATEWAY_RUN_COMMAND = "python3 -m uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-4280}"

DOT_REPLIT_TEMPLATE_PREFIX = '''# Generated by `free-agents deploy --replit` / `agent-toolbox deploy --replit`.
# Free Agents (agent-toolbox) gateway — see README and app/cli.py.

entrypoint = "app/main.py"

# Pin matches Replit docs example; update if Replit deprecates this module id.
modules = ["python-3.10:v18-20230807-322e88b"]

[nix]
channel = "stable-23_11"

[packager]
language = "python3"

[packager.features]
guessImports = true

# Editable install on boot: -q is fast on no-op; --disable-pip-version-check avoids slow checks.
# Skips heavy work when nothing changed; still reapplies if pyproject.toml / deps change.
onBoot = "python3 -m pip install -q --upgrade pip --disable-pip-version-check && python3 -m pip install -q -e . --disable-pip-version-check"
'''

DOT_REPLIT_TEMPLATE_SUFFIX = '''

[[ports]]
localPort = 4280
externalPort = 80

[gitHubImport]
requiredFiles = [".replit", "replit.nix"]
'''

REPLIT_NIX_TEMPLATE = """# Generated by `free-agents deploy --replit` / `agent-toolbox deploy --replit`.
{ pkgs }: {
  deps = [
    # Module ID pinned in .replit (python-3.10:v18-20230807-322e88b) must match a working Python stack.
    # If import / environment fails after a Replit update, find the current module id at:
    # https://replit.com/languages/python
    pkgs.python310
  ];
}
"""


def normalizeGithubOwnerRepo(input_url: str | None) -> str:
    if not input_url or not str(input_url).strip():
        return "unknown/unknown"
    s = str(input_url).strip()
    git_ssh = re.match(r"^git@github\.com:([^/]+)/(.+?)(\.git)?$", s, flags=re.IGNORECASE)
    if git_ssh:
        return f"{git_ssh.group(1)}/{git_ssh.group(2).removesuffix('.git')}"
    try:
        parse_target = s if "://" in s else f"https://{s}"
        parsed = urlparse(parse_target)
        host = parsed.netloc.lower().removeprefix("www.")
        if host == "github.com":
            parts = [p for p in parsed.path.strip("/").removesuffix(".git").split("/") if p]
            if len(parts) >= 2:
                return f"{parts[0]}/{parts[1]}"
    except Exception:
        pass
    if re.fullmatch(r"[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+", s):
        return s
    return "unknown/unknown"


def _owner_repo(owner_repo_slug: str) -> Tuple[str, str]:
    parts = [p for p in owner_repo_slug.strip("/").split("/") if p]
    if len(parts) != 2:
        print(f"Error: could not parse owner/repo from {owner_repo_slug!r}", file=sys.stderr)
        sys.exit(2)
    return parts[0], parts[1]


def _replit_import_url(owner_repo_slug: str) -> str:
    owner, repo = _owner_repo(owner_repo_slug)
    return f"{REPLIT_NEW_BASE}/github.com/{owner}/{repo}"


def _write_if_absent(path: Path, content: str, label: str) -> None:
    if path.exists():
        print(f"Keep existing {label}: {path}")
        return
    path.write_text(content, encoding="utf-8")
    print(f"Wrote {label}: {path}")


def _maybe_write_replit_nix(root: Path) -> None:
    nix = root / "replit.nix"
    toml = root / "replit.toml"
    if nix.exists() or toml.exists():
        if nix.exists():
            print(f"Keep existing replit.nix: {nix}")
        if toml.exists():
            print(f"Keep existing replit.toml: {toml}")
        return
    nix.write_text(REPLIT_NIX_TEMPLATE, encoding="utf-8")
    print(f"Wrote replit.nix: {nix}")


def _coerce_required_secrets(spec: dict[str, Any]) -> list[Tuple[str, str]]:
    raw = spec.get("required_secrets")
    if raw is None:
        raw = spec.get("requiredSecrets")
    if raw is None:
        raw = spec.get("secrets")

    rows: list[Tuple[str, str]] = []
    if isinstance(raw, list):
        for item in raw:
            if isinstance(item, str) and item.strip():
                rows.append((item.strip(), "Required by this agent."))
            elif isinstance(item, dict):
                name = str(item.get("name") or item.get("key") or "").strip()
                if not name:
                    continue
                desc = str(item.get("description") or item.get("purpose") or "Required by this agent.").strip()
                rows.append((name, desc))
    return rows


def _guess_repo_slug_from_spec(spec: dict[str, Any]) -> str:
    direct = normalizeGithubOwnerRepo(str(spec.get("github_url") or ""))
    if direct != "unknown/unknown":
        return direct
    if spec.get("repo_owner") and spec.get("repo_name"):
        slug = f"{str(spec.get('repo_owner')).strip()}/{str(spec.get('repo_name')).strip()}"
        parsed = normalizeGithubOwnerRepo(slug)
        if parsed != "unknown/unknown":
            return parsed
    prompt = str(spec.get("prompt") or "")
    m = re.search(r"\bfor the ([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+) repository\b", prompt)
    if m:
        parsed = normalizeGithubOwnerRepo(m.group(1))
        if parsed != "unknown/unknown":
            return parsed
    return "unknown/unknown"


def _resolve_run_command(spec: dict[str, Any], *, agent_id: str) -> str:
    run_command = str(spec.get("run_command") or "").strip()
    if run_command:
        return run_command
    print(
        f"Warning: agent '{agent_id}' has no run_command in stored spec; "
        f"falling back to default gateway command.",
        file=sys.stderr,
    )
    return DEFAULT_GATEWAY_RUN_COMMAND


def _print_replit_secrets(spec: dict[str, Any]) -> None:
    print()
    print("Add these in Replit (Tools → Secrets). Do not commit values to git.")
    print("Names and purpose only:")
    print()
    rows = _coerce_required_secrets(spec)
    if not rows:
        print("  • (none listed in this agent spec)")
        print()
        return
    for name, desc in rows:
        print(f"  • {name}: {desc}")
    print()


def _select_fuzzy_match(agent_query: str, matches: list[dict[str, Any]]) -> Optional[str]:
    needle = agent_query.strip().lower()
    if not needle:
        return None
    for m in matches:
        if str(m.get("name") or "").strip().lower() == needle:
            return str(m.get("id") or "").strip()
    for m in matches:
        mid = str(m.get("id") or "").strip().lower()
        mname = str(m.get("name") or "").strip().lower()
        if needle in mid or needle in mname:
            return str(m.get("id") or "").strip()
    return None


def _resolve_agent_spec(agent_ref: str) -> dict[str, Any]:
    exact = registry_store.get_agent(agent_ref)
    if exact is not None:
        return exact
    matches = registry_store.list_agents(q=agent_ref, latest_only=True)
    selected_id = _select_fuzzy_match(agent_ref, matches)
    if not selected_id:
        print(f"Agent not found: {agent_ref}", file=sys.stderr)
        sys.exit(2)
    selected = registry_store.get_agent(selected_id)
    if selected is None:
        print(f"Agent not found: {agent_ref}", file=sys.stderr)
        sys.exit(2)
    return selected


def _render_dot_replit(run_command: str) -> str:
    # `exec` ensures shell replacement so Ctrl+C signals behave naturally in Replit.
    run_line = f'run = ["bash", "-c", {json.dumps(f"exec {run_command}")}]'
    return DOT_REPLIT_TEMPLATE_PREFIX + "\n" + run_line + DOT_REPLIT_TEMPLATE_SUFFIX


def run_deploy_replit(agent_ref: str, *, root: Optional[Path] = None) -> None:
    """Prepare Replit config files for one registry agent and open import URL."""
    root = (root or Path.cwd()).resolve()
    spec = _resolve_agent_spec(agent_ref)
    resolved_id = str(spec.get("id") or agent_ref).strip()
    owner_repo_slug = _guess_repo_slug_from_spec(spec)
    if owner_repo_slug == "unknown/unknown":
        print(
            f"Error: agent '{resolved_id}' has no usable repository metadata "
            f"(expected github_url or repo_owner/repo_name).",
            file=sys.stderr,
        )
        sys.exit(2)
    run_command = _resolve_run_command(spec, agent_id=resolved_id)
    print(f"Agent: {resolved_id}")
    print(f"Repo: {owner_repo_slug}")

    _write_if_absent(root / ".replit", _render_dot_replit(run_command), ".replit")
    _maybe_write_replit_nix(root)

    _print_replit_secrets(spec)

    open_url = _replit_import_url(owner_repo_slug)
    print(f"Opening browser: {open_url}")
    webbrowser.open(open_url)

    print()
    print("After Replit opens:")
    print("Step 1: Add your secrets in Replit (Tools → Secrets)")
    print("Step 2: Click Run")
    print("Step 3: Your Free Agents gateway is live")
    print()
